language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

matrix:
    include:
        - php: 5.5.9
          env: setup=lowest
        - php: 5.5.9
          env: setup=stable
        - php: 7.0
          env: setup=stable
    allow_failures:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
    fast_finish: true

before_script:
  - phpenv rehash

script:
  - phpunit --configuration phpunit.xml --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - gjero@krsteski.de

