language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

script:
  - phpunit --configuration phpunit.xml --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - gjero@krsteski.de

